name: ci
on: push
jobs:
  ubuntu-job:
    name: ubuntu-job
    runs-on: ubuntu-latest
    steps:
    - name: show date
      run: date
  windows-job:
    name: windows-job
    runs-on: windows-latest
    steps:
    - name: show date
      run: date
  macos-job:
    name: macos-job
    runs-on: macos-latest
    steps:
    - name: show date
      run: date
  success-job:
    name: success-job
    runs-on: ubuntu-latest
    needs: [ubuntu-job, windows-job, macos-job]
    steps:
    - name: show success
      run: echo "All jobs completed"