name: ci
on: push
env:
  ARTIFACT_NAME: hello.txt
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: create
      run: echo "Hello World" >> "${{ env.ARTIFACT_NAME }}"
    - name: upload
      uses: actions/upload-artifact
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}